export default {
  skipFiles: [
    "v2/connectors/test/auth.test.sol",
    "v2/connectors/test/betamode.test.sol",
    "v2/connectors/test/compound.test.sol",
    "v2/connectors/test/emitEvent.test.sol",
    "v1/test/check.test.sol",
    "v1/test/InstaAccountV3.test.sol",
    "v1/test/InstaAccountV4.test.sol",
    "v1/test/staticConnector.test.sol",
    "v2/timelock/chiefTimelock.sol",
    "v2/timelock/timelock.sol",
    "v2/accounts/Implementation_default.v2.test.sol",
    "v2/accounts/Implementation_m2.test.sol",
    "v2/accounts/ImplementatioBetaTest.sol",
    "v2/proxy/connectorsProxy.sol",
    "v2/proxy/dummyConnectorsImpl.sol",
  ],
  istanbulReporter: ["html", "json"],
};
