/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AccountImplementations,
  AccountImplementationsInterface,
} from "../AccountImplementations";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_sig",
        type: "bytes4",
      },
    ],
    name: "getImplementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AccountImplementations__factory {
  static readonly abi = _abi;
  static createInterface(): AccountImplementationsInterface {
    return new utils.Interface(_abi) as AccountImplementationsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AccountImplementations {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AccountImplementations;
  }
}
