/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ConnectorInterface,
  ConnectorInterfaceInterface,
} from "../ConnectorInterface";

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ConnectorInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ConnectorInterfaceInterface {
    return new utils.Interface(_abi) as ConnectorInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ConnectorInterface {
    return new Contract(address, _abi, signerOrProvider) as ConnectorInterface;
  }
}
