/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  EventInterface,
  EventInterfaceInterface,
} from "../EventInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_connectorType",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_connectorID",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_eventCode",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_eventData",
        type: "bytes",
      },
    ],
    name: "emitEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class EventInterface__factory {
  static readonly abi = _abi;
  static createInterface(): EventInterfaceInterface {
    return new utils.Interface(_abi) as EventInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EventInterface {
    return new Contract(address, _abi, signerOrProvider) as EventInterface;
  }
}
