/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IndexInterface,
  IndexInterfaceInterface,
} from "../IndexInterface";

const _abi = [
  {
    inputs: [],
    name: "master",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IndexInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IndexInterfaceInterface {
    return new utils.Interface(_abi) as IndexInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IndexInterface {
    return new Contract(address, _abi, signerOrProvider) as IndexInterface;
  }
}
