/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { InstaMapping, InstaMappingInterface } from "../InstaMapping";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "cTokenMapping",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class InstaMapping__factory {
  static readonly abi = _abi;
  static createInterface(): InstaMappingInterface {
    return new utils.Interface(_abi) as InstaMappingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InstaMapping {
    return new Contract(address, _abi, signerOrProvider) as InstaMapping;
  }
}
