/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  InstaAccountV2,
  InstaAccountV2Interface,
} from "../InstaAccountV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_implementations",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "implementations",
    outputs: [
      {
        internalType: "contract AccountImplementations",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b506040516103c53803806103c58339818101604052602081101561003357600080fd5b81019080805190602001909291905050508073ffffffffffffffffffffffffffffffffffffffff1660808173ffffffffffffffffffffffffffffffffffffffff1660601b815250505060805160601c61032761009e60003980610119528061027952506103276000f3fe6080604052600436106100225760003560e01c806330e9012c146100d4576100a5565b366100a557600060e01b6000357fffffffff00000000000000000000000000000000000000000000000000000000167bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916146100a3576100a26000357fffffffff0000000000000000000000000000000000000000000000000000000016610115565b5b005b6100d26000357fffffffff0000000000000000000000000000000000000000000000000000000016610115565b005b3480156100e057600080fd5b506100e9610277565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b60007f000000000000000000000000000000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff1663dc9cc645836040518263ffffffff1660e01b815260040180827bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916815260200191505060206040518083038186803b1580156101a757600080fd5b505afa1580156101bb573d6000803e3d6000fd5b505050506040513d60208110156101d157600080fd5b81019080805190602001909291905050509050600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff16141561026a576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260308152602001806102c26030913960400191505060405180910390fd5b6102738161029b565b5050565b7f000000000000000000000000000000000000000000000000000000000000000081565b3660008037600080366000845af43d6000803e80600081146102bc573d6000f35b3d6000fdfe496e7374614163636f756e7456323a204e6f742061626c6520746f2066696e64205f696d706c656d656e746174696f6ea2646970667358221220d2004e3b9ab5a5bc3863638349f91acbe5c12a4ccc59838585860886186164da64736f6c63430007000033";

type InstaAccountV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InstaAccountV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InstaAccountV2__factory extends ContractFactory {
  constructor(...args: InstaAccountV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    _implementations: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<InstaAccountV2> {
    return super.deploy(
      _implementations,
      overrides || {}
    ) as Promise<InstaAccountV2>;
  }
  getDeployTransaction(
    _implementations: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_implementations, overrides || {});
  }
  attach(address: string): InstaAccountV2 {
    return super.attach(address) as InstaAccountV2;
  }
  connect(signer: Signer): InstaAccountV2__factory {
    return super.connect(signer) as InstaAccountV2__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InstaAccountV2Interface {
    return new utils.Interface(_abi) as InstaAccountV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InstaAccountV2 {
    return new Contract(address, _abi, signerOrProvider) as InstaAccountV2;
  }
}
