/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AccountInterfaceInterface extends utils.Interface {
  functions: {
    "disable(address)": FunctionFragment;
    "enable(address)": FunctionFragment;
    "isAuth(address)": FunctionFragment;
    "isBeta()": FunctionFragment;
    "toggleBeta()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "disable", values: [string]): string;
  encodeFunctionData(functionFragment: "enable", values: [string]): string;
  encodeFunctionData(functionFragment: "isAuth", values: [string]): string;
  encodeFunctionData(functionFragment: "isBeta", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "toggleBeta",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "disable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAuth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isBeta", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toggleBeta", data: BytesLike): Result;

  events: {};
}

export interface AccountInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AccountInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    disable(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enable(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isAuth(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isBeta(overrides?: CallOverrides): Promise<[boolean]>;

    toggleBeta(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  disable(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enable(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isAuth(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isBeta(overrides?: CallOverrides): Promise<boolean>;

  toggleBeta(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    disable(arg0: string, overrides?: CallOverrides): Promise<void>;

    enable(arg0: string, overrides?: CallOverrides): Promise<void>;

    isAuth(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isBeta(overrides?: CallOverrides): Promise<boolean>;

    toggleBeta(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    disable(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enable(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isAuth(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isBeta(overrides?: CallOverrides): Promise<BigNumber>;

    toggleBeta(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    disable(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enable(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isAuth(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBeta(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    toggleBeta(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
