/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ConnectAuthInterface extends utils.Interface {
  functions: {
    "addModule(address)": FunctionFragment;
    "connectorID()": FunctionFragment;
    "getEventAddr()": FunctionFragment;
    "name()": FunctionFragment;
    "removeModule(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addModule", values: [string]): string;
  encodeFunctionData(
    functionFragment: "connectorID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEventAddr",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeModule",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "addModule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "connectorID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeModule",
    data: BytesLike
  ): Result;

  events: {
    "LogAddAuth(address,address)": EventFragment;
    "LogRemoveAuth(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogAddAuth"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogRemoveAuth"): EventFragment;
}

export type LogAddAuthEvent = TypedEvent<
  [string, string],
  { _msgSender: string; _auth: string }
>;

export type LogAddAuthEventFilter = TypedEventFilter<LogAddAuthEvent>;

export type LogRemoveAuthEvent = TypedEvent<
  [string, string],
  { _msgSender: string; _auth: string }
>;

export type LogRemoveAuthEventFilter = TypedEventFilter<LogRemoveAuthEvent>;

export interface ConnectAuth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConnectAuthInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addModule(
      user: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    connectorID(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

    getEventAddr(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    removeModule(
      user: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addModule(
    user: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  connectorID(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

  getEventAddr(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  removeModule(
    user: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addModule(user: string, overrides?: CallOverrides): Promise<void>;

    connectorID(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

    getEventAddr(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    removeModule(user: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "LogAddAuth(address,address)"(
      _msgSender?: string | null,
      _auth?: string | null
    ): LogAddAuthEventFilter;
    LogAddAuth(
      _msgSender?: string | null,
      _auth?: string | null
    ): LogAddAuthEventFilter;

    "LogRemoveAuth(address,address)"(
      _msgSender?: string | null,
      _auth?: string | null
    ): LogRemoveAuthEventFilter;
    LogRemoveAuth(
      _msgSender?: string | null,
      _auth?: string | null
    ): LogRemoveAuthEventFilter;
  };

  estimateGas: {
    addModule(
      user: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    connectorID(overrides?: CallOverrides): Promise<BigNumber>;

    getEventAddr(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    removeModule(
      user: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addModule(
      user: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    connectorID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEventAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeModule(
      user: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
