/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ConnectBasicInterface extends utils.Interface {
  functions: {
    "connectorID()": FunctionFragment;
    "deposit(address,uint256,uint256,uint256)": FunctionFragment;
    "getEthAddr()": FunctionFragment;
    "getEventAddr()": FunctionFragment;
    "getMemoryAddr()": FunctionFragment;
    "name()": FunctionFragment;
    "withdraw(address,uint256,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "connectorID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEventAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMemoryAddr",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "connectorID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEthAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemoryAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "LogDeposit(address,uint256,uint256,uint256)": EventFragment;
    "LogWithdraw(address,uint256,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogWithdraw"): EventFragment;
}

export type LogDepositEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  { erc20: string; tokenAmt: BigNumber; getId: BigNumber; setId: BigNumber }
>;

export type LogDepositEventFilter = TypedEventFilter<LogDepositEvent>;

export type LogWithdrawEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber],
  {
    erc20: string;
    tokenAmt: BigNumber;
    to: string;
    getId: BigNumber;
    setId: BigNumber;
  }
>;

export type LogWithdrawEventFilter = TypedEventFilter<LogWithdrawEvent>;

export interface ConnectBasic extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConnectBasicInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    connectorID(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

    deposit(
      erc20: string,
      tokenAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getEthAddr(overrides?: CallOverrides): Promise<[string]>;

    getEventAddr(overrides?: CallOverrides): Promise<[string]>;

    getMemoryAddr(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      erc20: string,
      tokenAmt: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  connectorID(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

  deposit(
    erc20: string,
    tokenAmt: BigNumberish,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getEthAddr(overrides?: CallOverrides): Promise<string>;

  getEventAddr(overrides?: CallOverrides): Promise<string>;

  getMemoryAddr(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  withdraw(
    erc20: string,
    tokenAmt: BigNumberish,
    to: string,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    connectorID(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

    deposit(
      erc20: string,
      tokenAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getEthAddr(overrides?: CallOverrides): Promise<string>;

    getEventAddr(overrides?: CallOverrides): Promise<string>;

    getMemoryAddr(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    withdraw(
      erc20: string,
      tokenAmt: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "LogDeposit(address,uint256,uint256,uint256)"(
      erc20?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogDepositEventFilter;
    LogDeposit(
      erc20?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogDepositEventFilter;

    "LogWithdraw(address,uint256,address,uint256,uint256)"(
      erc20?: string | null,
      tokenAmt?: null,
      to?: string | null,
      getId?: null,
      setId?: null
    ): LogWithdrawEventFilter;
    LogWithdraw(
      erc20?: string | null,
      tokenAmt?: null,
      to?: string | null,
      getId?: null,
      setId?: null
    ): LogWithdrawEventFilter;
  };

  estimateGas: {
    connectorID(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      erc20: string,
      tokenAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getEthAddr(overrides?: CallOverrides): Promise<BigNumber>;

    getEventAddr(overrides?: CallOverrides): Promise<BigNumber>;

    getMemoryAddr(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      erc20: string,
      tokenAmt: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    connectorID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      erc20: string,
      tokenAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getEthAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEventAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMemoryAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      erc20: string,
      tokenAmt: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
