/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ConnectorsInterfaceInterface extends utils.Interface {
  functions: {
    "isConnectors(string[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isConnectors",
    values: [string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "isConnectors",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ConnectorsInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConnectorsInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isConnectors(
      connectorNames: string[],
      overrides?: CallOverrides
    ): Promise<[boolean, string[]]>;
  };

  isConnectors(
    connectorNames: string[],
    overrides?: CallOverrides
  ): Promise<[boolean, string[]]>;

  callStatic: {
    isConnectors(
      connectorNames: string[],
      overrides?: CallOverrides
    ): Promise<[boolean, string[]]>;
  };

  filters: {};

  estimateGas: {
    isConnectors(
      connectorNames: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isConnectors(
      connectorNames: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
