/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface EventsInterface extends utils.Interface {
  functions: {};

  events: {
    "LogDisableBeta()": EventFragment;
    "LogEnableBeta()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogDisableBeta"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogEnableBeta"): EventFragment;
}

export type LogDisableBetaEvent = TypedEvent<[], {}>;

export type LogDisableBetaEventFilter = TypedEventFilter<LogDisableBetaEvent>;

export type LogEnableBetaEvent = TypedEvent<[], {}>;

export type LogEnableBetaEventFilter = TypedEventFilter<LogEnableBetaEvent>;

export interface Events extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "LogDisableBeta()"(): LogDisableBetaEventFilter;
    LogDisableBeta(): LogDisableBetaEventFilter;

    "LogEnableBeta()"(): LogEnableBetaEventFilter;
    LogEnableBeta(): LogEnableBetaEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
