/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "TimelockController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimelockController__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "TransparentUpgradeableProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransparentUpgradeableProxy__factory>;
    getContractFactory(
      name: "UpgradeableProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeableProxy__factory>;
    getContractFactory(
      name: "AccountInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountInterface__factory>;
    getContractFactory(
      name: "AddressIndex",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressIndex__factory>;
    getContractFactory(
      name: "CloneFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CloneFactory__factory>;
    getContractFactory(
      name: "InstaIndex",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaIndex__factory>;
    getContractFactory(
      name: "ListInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListInterface__factory>;
    getContractFactory(
      name: "AccountInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountInterface__factory>;
    getContractFactory(
      name: "Configure",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Configure__factory>;
    getContractFactory(
      name: "InstaList",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaList__factory>;
    getContractFactory(
      name: "Variables",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Variables__factory>;
    getContractFactory(
      name: "CheckInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CheckInterface__factory>;
    getContractFactory(
      name: "ConnectorsInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectorsInterface__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaAccount__factory>;
    getContractFactory(
      name: "ListInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListInterface__factory>;
    getContractFactory(
      name: "Record",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Record__factory>;
    getContractFactory(
      name: "ConnectorInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectorInterface__factory>;
    getContractFactory(
      name: "Controllers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Controllers__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaConnectors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaConnectors__factory>;
    getContractFactory(
      name: "Listings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Listings__factory>;
    getContractFactory(
      name: "AccountInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountInterface__factory>;
    getContractFactory(
      name: "Auth",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Auth__factory>;
    getContractFactory(
      name: "Basics",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Basics__factory>;
    getContractFactory(
      name: "ConnectAuth",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectAuth__factory>;
    getContractFactory(
      name: "EventInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventInterface__factory>;
    getContractFactory(
      name: "AccountInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountInterface__factory>;
    getContractFactory(
      name: "BasicResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasicResolver__factory>;
    getContractFactory(
      name: "ConnectBasic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectBasic__factory>;
    getContractFactory(
      name: "ERC20Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Interface__factory>;
    getContractFactory(
      name: "EventInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventInterface__factory>;
    getContractFactory(
      name: "Memory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Memory__factory>;
    getContractFactory(
      name: "MemoryInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MemoryInterface__factory>;
    getContractFactory(
      name: "InstaEvent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaEvent__factory>;
    getContractFactory(
      name: "ListInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListInterface__factory>;
    getContractFactory(
      name: "InstaMemory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaMemory__factory>;
    getContractFactory(
      name: "Constants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Constants__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaDefaultImplementation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaDefaultImplementation__factory>;
    getContractFactory(
      name: "ListInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListInterface__factory>;
    getContractFactory(
      name: "Record",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Record__factory>;
    getContractFactory(
      name: "ConnectorsInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectorsInterface__factory>;
    getContractFactory(
      name: "Constants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Constants__factory>;
    getContractFactory(
      name: "InstaImplementationM1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaImplementationM1__factory>;
    getContractFactory(
      name: "CheckInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CheckInterface__factory>;
    getContractFactory(
      name: "CommonSetup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CommonSetup__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaDefaultImplementationV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaDefaultImplementationV2__factory>;
    getContractFactory(
      name: "ListInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListInterface__factory>;
    getContractFactory(
      name: "Record",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Record__factory>;
    getContractFactory(
      name: "CheckInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CheckInterface__factory>;
    getContractFactory(
      name: "ConnectorsInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectorsInterface__factory>;
    getContractFactory(
      name: "DefaultImplementation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DefaultImplementation__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaImplementationM2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaImplementationM2__factory>;
    getContractFactory(
      name: "ConnectorsInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectorsInterface__factory>;
    getContractFactory(
      name: "Constants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Constants__factory>;
    getContractFactory(
      name: "InstaImplementationBetaTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaImplementationBetaTest__factory>;
    getContractFactory(
      name: "AccountInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountInterface__factory>;
    getContractFactory(
      name: "Auth",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Auth__factory>;
    getContractFactory(
      name: "ConnectV2Auth",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectV2Auth__factory>;
    getContractFactory(
      name: "ListInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListInterface__factory>;
    getContractFactory(
      name: "AccountInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountInterface__factory>;
    getContractFactory(
      name: "ConnectV2Beta",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectV2Beta__factory>;
    getContractFactory(
      name: "Events",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Events__factory>;
    getContractFactory(
      name: "Resolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Resolver__factory>;
    getContractFactory(
      name: "BasicResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasicResolver__factory>;
    getContractFactory(
      name: "CETHInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CETHInterface__factory>;
    getContractFactory(
      name: "ComptrollerInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComptrollerInterface__factory>;
    getContractFactory(
      name: "ConnectCompound",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectCompound__factory>;
    getContractFactory(
      name: "CTokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CTokenInterface__factory>;
    getContractFactory(
      name: "InstaMapping",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaMapping__factory>;
    getContractFactory(
      name: "MemoryInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MemoryInterface__factory>;
    getContractFactory(
      name: "TokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenInterface__factory>;
    getContractFactory(
      name: "ConnectV2EmitEvent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectV2EmitEvent__factory>;
    getContractFactory(
      name: "AccountImplementations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountImplementations__factory>;
    getContractFactory(
      name: "InstaAccountV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaAccountV2__factory>;
    getContractFactory(
      name: "InstaConnectorsV2Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaConnectorsV2Proxy__factory>;
    getContractFactory(
      name: "ConnectorInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConnectorInterface__factory>;
    getContractFactory(
      name: "Controllers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Controllers__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaConnectorsV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaConnectorsV2__factory>;
    getContractFactory(
      name: "Implementations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Implementations__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaImplementations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaImplementations__factory>;
    getContractFactory(
      name: "Setup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Setup__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaChiefTimelockContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaChiefTimelockContract__factory>;
    getContractFactory(
      name: "IndexInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexInterface__factory>;
    getContractFactory(
      name: "InstaTimelockContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaTimelockContract__factory>;

    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "TimelockController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TimelockController>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "TransparentUpgradeableProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TransparentUpgradeableProxy>;
    getContractAt(
      name: "UpgradeableProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeableProxy>;
    getContractAt(
      name: "AccountInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountInterface>;
    getContractAt(
      name: "AddressIndex",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressIndex>;
    getContractAt(
      name: "CloneFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CloneFactory>;
    getContractAt(
      name: "InstaIndex",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaIndex>;
    getContractAt(
      name: "ListInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ListInterface>;
    getContractAt(
      name: "AccountInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountInterface>;
    getContractAt(
      name: "Configure",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Configure>;
    getContractAt(
      name: "InstaList",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaList>;
    getContractAt(
      name: "Variables",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Variables>;
    getContractAt(
      name: "CheckInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CheckInterface>;
    getContractAt(
      name: "ConnectorsInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectorsInterface>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaAccount",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaAccount>;
    getContractAt(
      name: "ListInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ListInterface>;
    getContractAt(
      name: "Record",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Record>;
    getContractAt(
      name: "ConnectorInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectorInterface>;
    getContractAt(
      name: "Controllers",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Controllers>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaConnectors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaConnectors>;
    getContractAt(
      name: "Listings",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Listings>;
    getContractAt(
      name: "AccountInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountInterface>;
    getContractAt(
      name: "Auth",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Auth>;
    getContractAt(
      name: "Basics",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Basics>;
    getContractAt(
      name: "ConnectAuth",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectAuth>;
    getContractAt(
      name: "EventInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EventInterface>;
    getContractAt(
      name: "AccountInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountInterface>;
    getContractAt(
      name: "BasicResolver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BasicResolver>;
    getContractAt(
      name: "ConnectBasic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectBasic>;
    getContractAt(
      name: "ERC20Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Interface>;
    getContractAt(
      name: "EventInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EventInterface>;
    getContractAt(
      name: "Memory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Memory>;
    getContractAt(
      name: "MemoryInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MemoryInterface>;
    getContractAt(
      name: "InstaEvent",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaEvent>;
    getContractAt(
      name: "ListInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ListInterface>;
    getContractAt(
      name: "InstaMemory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaMemory>;
    getContractAt(
      name: "Constants",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Constants>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaDefaultImplementation",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaDefaultImplementation>;
    getContractAt(
      name: "ListInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ListInterface>;
    getContractAt(
      name: "Record",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Record>;
    getContractAt(
      name: "ConnectorsInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectorsInterface>;
    getContractAt(
      name: "Constants",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Constants>;
    getContractAt(
      name: "InstaImplementationM1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaImplementationM1>;
    getContractAt(
      name: "CheckInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CheckInterface>;
    getContractAt(
      name: "CommonSetup",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CommonSetup>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaDefaultImplementationV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaDefaultImplementationV2>;
    getContractAt(
      name: "ListInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ListInterface>;
    getContractAt(
      name: "Record",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Record>;
    getContractAt(
      name: "CheckInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CheckInterface>;
    getContractAt(
      name: "ConnectorsInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectorsInterface>;
    getContractAt(
      name: "DefaultImplementation",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DefaultImplementation>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaImplementationM2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaImplementationM2>;
    getContractAt(
      name: "ConnectorsInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectorsInterface>;
    getContractAt(
      name: "Constants",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Constants>;
    getContractAt(
      name: "InstaImplementationBetaTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaImplementationBetaTest>;
    getContractAt(
      name: "AccountInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountInterface>;
    getContractAt(
      name: "Auth",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Auth>;
    getContractAt(
      name: "ConnectV2Auth",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectV2Auth>;
    getContractAt(
      name: "ListInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ListInterface>;
    getContractAt(
      name: "AccountInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountInterface>;
    getContractAt(
      name: "ConnectV2Beta",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectV2Beta>;
    getContractAt(
      name: "Events",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Events>;
    getContractAt(
      name: "Resolver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Resolver>;
    getContractAt(
      name: "BasicResolver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BasicResolver>;
    getContractAt(
      name: "CETHInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CETHInterface>;
    getContractAt(
      name: "ComptrollerInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ComptrollerInterface>;
    getContractAt(
      name: "ConnectCompound",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectCompound>;
    getContractAt(
      name: "CTokenInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CTokenInterface>;
    getContractAt(
      name: "InstaMapping",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaMapping>;
    getContractAt(
      name: "MemoryInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MemoryInterface>;
    getContractAt(
      name: "TokenInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenInterface>;
    getContractAt(
      name: "ConnectV2EmitEvent",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectV2EmitEvent>;
    getContractAt(
      name: "AccountImplementations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountImplementations>;
    getContractAt(
      name: "InstaAccountV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaAccountV2>;
    getContractAt(
      name: "InstaConnectorsV2Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaConnectorsV2Proxy>;
    getContractAt(
      name: "ConnectorInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ConnectorInterface>;
    getContractAt(
      name: "Controllers",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Controllers>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaConnectorsV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaConnectorsV2>;
    getContractAt(
      name: "Implementations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Implementations>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaImplementations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaImplementations>;
    getContractAt(
      name: "Setup",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Setup>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaChiefTimelockContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaChiefTimelockContract>;
    getContractAt(
      name: "IndexInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexInterface>;
    getContractAt(
      name: "InstaTimelockContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaTimelockContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
