/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface InstaConnectorsInterface extends utils.Interface {
  functions: {
    "chief(address)": FunctionFragment;
    "connectorArray(uint256)": FunctionFragment;
    "connectorCount()": FunctionFragment;
    "connectorLength()": FunctionFragment;
    "connectors(address)": FunctionFragment;
    "disable(address)": FunctionFragment;
    "disableChief(address)": FunctionFragment;
    "enable(address)": FunctionFragment;
    "enableChief(address)": FunctionFragment;
    "enableStatic(address)": FunctionFragment;
    "instaIndex()": FunctionFragment;
    "isConnector(address[])": FunctionFragment;
    "isStaticConnector(address[])": FunctionFragment;
    "staticConnectorArray(uint256)": FunctionFragment;
    "staticConnectorLength()": FunctionFragment;
    "staticConnectors(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "chief", values: [string]): string;
  encodeFunctionData(
    functionFragment: "connectorArray",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "connectorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorLength",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "connectors", values: [string]): string;
  encodeFunctionData(functionFragment: "disable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "disableChief",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "enable", values: [string]): string;
  encodeFunctionData(functionFragment: "enableChief", values: [string]): string;
  encodeFunctionData(
    functionFragment: "enableStatic",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "instaIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isConnector",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isStaticConnector",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "staticConnectorArray",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "staticConnectorLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "staticConnectors",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "chief", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "connectorArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "connectors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableChief",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enableChief",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableStatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "instaIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isConnector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStaticConnector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "staticConnectorArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "staticConnectorLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "staticConnectors",
    data: BytesLike
  ): Result;

  events: {
    "LogAddController(address)": EventFragment;
    "LogDisable(address)": EventFragment;
    "LogEnable(address)": EventFragment;
    "LogEnableStatic(address)": EventFragment;
    "LogRemoveController(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogAddController"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogDisable"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogEnable"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogEnableStatic"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogRemoveController"): EventFragment;
}

export type LogAddControllerEvent = TypedEvent<[string], { addr: string }>;

export type LogAddControllerEventFilter = TypedEventFilter<LogAddControllerEvent>;

export type LogDisableEvent = TypedEvent<[string], { connector: string }>;

export type LogDisableEventFilter = TypedEventFilter<LogDisableEvent>;

export type LogEnableEvent = TypedEvent<[string], { connector: string }>;

export type LogEnableEventFilter = TypedEventFilter<LogEnableEvent>;

export type LogEnableStaticEvent = TypedEvent<[string], { connector: string }>;

export type LogEnableStaticEventFilter = TypedEventFilter<LogEnableStaticEvent>;

export type LogRemoveControllerEvent = TypedEvent<[string], { addr: string }>;

export type LogRemoveControllerEventFilter = TypedEventFilter<LogRemoveControllerEvent>;

export interface InstaConnectors extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InstaConnectorsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    chief(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    connectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    connectorCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    connectorLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    connectors(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    disable(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    disableChief(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enable(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enableChief(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enableStatic(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    instaIndex(overrides?: CallOverrides): Promise<[string]>;

    isConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<[boolean] & { isOk: boolean }>;

    isStaticConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<[boolean] & { isOk: boolean }>;

    staticConnectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    staticConnectorLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    staticConnectors(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  chief(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  connectorArray(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  connectorCount(overrides?: CallOverrides): Promise<BigNumber>;

  connectorLength(overrides?: CallOverrides): Promise<BigNumber>;

  connectors(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  disable(
    _connector: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  disableChief(
    _userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enable(
    _connector: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enableChief(
    _userAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enableStatic(
    _connector: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  instaIndex(overrides?: CallOverrides): Promise<string>;

  isConnector(
    _connectors: string[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  isStaticConnector(
    _connectors: string[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  staticConnectorArray(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  staticConnectorLength(overrides?: CallOverrides): Promise<BigNumber>;

  staticConnectors(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    chief(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    connectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    connectorCount(overrides?: CallOverrides): Promise<BigNumber>;

    connectorLength(overrides?: CallOverrides): Promise<BigNumber>;

    connectors(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    disable(_connector: string, overrides?: CallOverrides): Promise<void>;

    disableChief(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    enable(_connector: string, overrides?: CallOverrides): Promise<void>;

    enableChief(_userAddress: string, overrides?: CallOverrides): Promise<void>;

    enableStatic(_connector: string, overrides?: CallOverrides): Promise<void>;

    instaIndex(overrides?: CallOverrides): Promise<string>;

    isConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    isStaticConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    staticConnectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    staticConnectorLength(overrides?: CallOverrides): Promise<BigNumber>;

    staticConnectors(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "LogAddController(address)"(
      addr?: string | null
    ): LogAddControllerEventFilter;
    LogAddController(addr?: string | null): LogAddControllerEventFilter;

    "LogDisable(address)"(connector?: string | null): LogDisableEventFilter;
    LogDisable(connector?: string | null): LogDisableEventFilter;

    "LogEnable(address)"(connector?: string | null): LogEnableEventFilter;
    LogEnable(connector?: string | null): LogEnableEventFilter;

    "LogEnableStatic(address)"(
      connector?: string | null
    ): LogEnableStaticEventFilter;
    LogEnableStatic(connector?: string | null): LogEnableStaticEventFilter;

    "LogRemoveController(address)"(
      addr?: string | null
    ): LogRemoveControllerEventFilter;
    LogRemoveController(addr?: string | null): LogRemoveControllerEventFilter;
  };

  estimateGas: {
    chief(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    connectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    connectorCount(overrides?: CallOverrides): Promise<BigNumber>;

    connectorLength(overrides?: CallOverrides): Promise<BigNumber>;

    connectors(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    disable(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    disableChief(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enable(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enableChief(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enableStatic(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    instaIndex(overrides?: CallOverrides): Promise<BigNumber>;

    isConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isStaticConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    staticConnectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    staticConnectorLength(overrides?: CallOverrides): Promise<BigNumber>;

    staticConnectors(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    chief(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    connectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    connectorCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectors(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    disable(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    disableChief(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enable(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enableChief(
      _userAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enableStatic(
      _connector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    instaIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isStaticConnector(
      _connectors: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    staticConnectorArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    staticConnectorLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    staticConnectors(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
