/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RecordInterface extends utils.Interface {
  functions: {
    "disable(address)": FunctionFragment;
    "editCheckMapping(address,bool)": FunctionFragment;
    "enable(address)": FunctionFragment;
    "implementationVersion()": FunctionFragment;
    "instaIndex()": FunctionFragment;
    "isAuth(address)": FunctionFragment;
    "shield()": FunctionFragment;
    "switchShield(bool)": FunctionFragment;
    "version()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "disable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "editCheckMapping",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "enable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "implementationVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "instaIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isAuth", values: [string]): string;
  encodeFunctionData(functionFragment: "shield", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "switchShield",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "disable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "editCheckMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementationVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "instaIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAuth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "switchShield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "LogCheckMapping(address,bool)": EventFragment;
    "LogDisableUser(address)": EventFragment;
    "LogEnableUser(address)": EventFragment;
    "LogSwitchShield(bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogCheckMapping"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogDisableUser"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogEnableUser"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSwitchShield"): EventFragment;
}

export type LogCheckMappingEvent = TypedEvent<
  [string, boolean],
  { user: string; check: boolean }
>;

export type LogCheckMappingEventFilter = TypedEventFilter<LogCheckMappingEvent>;

export type LogDisableUserEvent = TypedEvent<[string], { user: string }>;

export type LogDisableUserEventFilter = TypedEventFilter<LogDisableUserEvent>;

export type LogEnableUserEvent = TypedEvent<[string], { user: string }>;

export type LogEnableUserEventFilter = TypedEventFilter<LogEnableUserEvent>;

export type LogSwitchShieldEvent = TypedEvent<[boolean], { _shield: boolean }>;

export type LogSwitchShieldEventFilter = TypedEventFilter<LogSwitchShieldEvent>;

export interface Record extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RecordInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    disable(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    editCheckMapping(
      user: string,
      _bool: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enable(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    implementationVersion(overrides?: CallOverrides): Promise<[BigNumber]>;

    instaIndex(overrides?: CallOverrides): Promise<[string]>;

    isAuth(user: string, overrides?: CallOverrides): Promise<[boolean]>;

    shield(overrides?: CallOverrides): Promise<[boolean]>;

    switchShield(
      _shield: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  disable(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  editCheckMapping(
    user: string,
    _bool: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enable(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  implementationVersion(overrides?: CallOverrides): Promise<BigNumber>;

  instaIndex(overrides?: CallOverrides): Promise<string>;

  isAuth(user: string, overrides?: CallOverrides): Promise<boolean>;

  shield(overrides?: CallOverrides): Promise<boolean>;

  switchShield(
    _shield: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    disable(user: string, overrides?: CallOverrides): Promise<void>;

    editCheckMapping(
      user: string,
      _bool: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    enable(user: string, overrides?: CallOverrides): Promise<void>;

    implementationVersion(overrides?: CallOverrides): Promise<BigNumber>;

    instaIndex(overrides?: CallOverrides): Promise<string>;

    isAuth(user: string, overrides?: CallOverrides): Promise<boolean>;

    shield(overrides?: CallOverrides): Promise<boolean>;

    switchShield(_shield: boolean, overrides?: CallOverrides): Promise<void>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "LogCheckMapping(address,bool)"(
      user?: null,
      check?: null
    ): LogCheckMappingEventFilter;
    LogCheckMapping(user?: null, check?: null): LogCheckMappingEventFilter;

    "LogDisableUser(address)"(user?: string | null): LogDisableUserEventFilter;
    LogDisableUser(user?: string | null): LogDisableUserEventFilter;

    "LogEnableUser(address)"(user?: string | null): LogEnableUserEventFilter;
    LogEnableUser(user?: string | null): LogEnableUserEventFilter;

    "LogSwitchShield(bool)"(_shield?: null): LogSwitchShieldEventFilter;
    LogSwitchShield(_shield?: null): LogSwitchShieldEventFilter;
  };

  estimateGas: {
    disable(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    editCheckMapping(
      user: string,
      _bool: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enable(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    implementationVersion(overrides?: CallOverrides): Promise<BigNumber>;

    instaIndex(overrides?: CallOverrides): Promise<BigNumber>;

    isAuth(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    shield(overrides?: CallOverrides): Promise<BigNumber>;

    switchShield(
      _shield: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    disable(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    editCheckMapping(
      user: string,
      _bool: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enable(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    implementationVersion(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    instaIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAuth(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    shield(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    switchShield(
      _shield: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
